'use strict';
const MAX=512*1024, buckets=new Map();
const clean=(v,n)=>String(v==null?'':v).trim().slice(0,n);
function originOk(req){const o=clean(req.headers.origin,500);if(!o)return true;let h;try{h=new URL(o).hostname.toLowerCase();}catch(_){return false;}return h==='wms-packem.vercel.app'||/^wms-packem-[a-z0-9-]+\.vercel\.app$/i.test(h)||h==='localhost'||h==='127.0.0.1';}
function limited(req){const ip=clean((req.headers['x-forwarded-for']||'').split(',')[0]||req.socket?.remoteAddress,100),now=Date.now(),b=buckets.get(ip);if(!b||now-b.at>60000){buckets.set(ip,{at:now,n:1});return false;}return ++b.n>180;}
function body(req){if(Number(req.headers['content-length'])>MAX)throw Object.assign(Error('Dados excedem o limite'),{status:413});const b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!b||typeof b!=='object')throw Object.assign(Error('JSON inválido'),{status:400});return b;}
function env(){const url=clean(process.env.SUPABASE_URL,500).replace(/\/$/,''),key=clean(process.env.SUPABASE_SERVICE_ROLE_KEY,1000);if(!url||!key)throw Object.assign(Error('Sincronização fiscal não configurada no servidor'),{status:500});return {url,key};}
async function db(path,method,payload){const {url,key}=env(),r=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,authorization:'Bearer '+key,'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:payload===undefined?undefined:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>null);throw Object.assign(Error(d&&d.message||'Banco recusou a alteração fiscal'),{status:502});}}
function labels(rows,max){max=max||200;if(!Array.isArray(rows)||rows.length>max)throw Object.assign(Error('Lote de etiquetas inválido'),{status:400});return rows.map(r=>{if(!r||!clean(r.id,120))throw Object.assign(Error('Etiqueta inválida'),{status:400});return r;});}
async function run(b){const a=clean(b.action,40),at=new Date().toISOString();
 if(a==='upsert_labels')return db('etiquetas','POST',labels(b.rows));
 if(a==='delete_labels'){const ids=(b.ids||[]).map(x=>clean(x,120)).filter(Boolean);if(!ids.length||ids.length>200)throw Object.assign(Error('IDs inválidos'),{status:400});return db('etiquetas?id=in.('+ids.map(encodeURIComponent).join(',')+')','DELETE');}
 if(a==='reconcile_labels'){const key=clean(b.doc_key,200),rows=labels(b.rows||[],1000);if(!key)throw Object.assign(Error('Documento fiscal inválido'),{status:400});if(rows.some(r=>clean(r.doc_key,200)!==key))throw Object.assign(Error('Etiqueta fora do documento'),{status:400});const ids=rows.map(r=>clean(r.id,120));let path='etiquetas?doc_key=eq.'+encodeURIComponent(key);if(ids.length)path+='&id=not.in.('+ids.map(encodeURIComponent).join(',')+')';await db(path,'DELETE');for(let i=0;i<rows.length;i+=200)await db('etiquetas','POST',rows.slice(i,i+200));return;}
 if(a==='upsert_note'||a==='upsert_rom'){const row=b.row;if(!row||!clean(row.key,200)||!row.data)throw Object.assign(Error('Documento inválido'),{status:400});return db((a==='upsert_note'?'notas_fiscais':'romaneios'),'POST',{key:clean(row.key,200),data:row.data,updated_at:row.updated_at||at});}
 if(a==='delete_note'||a==='delete_rom'){const key=clean(b.key,200);if(!key)throw Object.assign(Error('Chave inválida'),{status:400});return db((a==='delete_note'?'notas_fiscais':'romaneios'),'POST',{key,data:{key,deleted:true,deletedAt:at},updated_at:at});}
 throw Object.assign(Error('Ação inválida'),{status:400});
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-WMS-Request');if(req.method==='OPTIONS')return res.status(204).end();if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método não permitido'});if(!originOk(req))return res.status(403).json({ok:false,error:'Origem não autorizada'});if(limited(req))return res.status(429).json({ok:false,error:'Muitas operações'});try{await run(body(req));return res.status(200).json({ok:true});}catch(e){const s=Number(e.status)||500;if(s>=500)console.error('[fiscal-sync]',e);return res.status(s).json({ok:false,error:clean(e.message,300)});}};
module.exports._test={originOk,body,labels,run};
