'use strict';
const crypto=require('crypto');
const MAX=512*1024, buckets=new Map();
const clean=(v,n)=>String(v==null?'':v).trim().slice(0,n);
function originOk(req){const o=clean(req.headers.origin,500);if(!o)return true;let h;try{h=new URL(o).hostname.toLowerCase();}catch(_){return false;}return h==='wms-packem.vercel.app'||/^wms-packem-[a-z0-9-]+\.vercel\.app$/i.test(h)||h==='localhost'||h==='127.0.0.1';}
function limited(req){const ip=clean((req.headers['x-forwarded-for']||'').split(',')[0]||req.socket?.remoteAddress,100),now=Date.now(),b=buckets.get(ip);if(!b||now-b.at>60000){buckets.set(ip,{at:now,n:1});return false;}return ++b.n>180;}
function body(req){if(Number(req.headers['content-length'])>MAX)throw Object.assign(Error('Dados excedem o limite'),{status:413});const b=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!b||typeof b!=='object')throw Object.assign(Error('JSON inválido'),{status:400});return b;}
/* A chave publishable já é pública no navegador. Ela mantém a leitura central funcionando
   enquanto a Vercel não tem a service_role; as políticas do Supabase continuam valendo. */
const PUBLIC_URL='https://aekqhtutrfwjoebsebeq.supabase.co';
const PUBLIC_KEY='sb_publishable_fx7cQutj5eGGFFrPGA7yBA_GtFkaVXN';
function env(){const service=clean(process.env.SUPABASE_SERVICE_ROLE_KEY,1000),url=clean(process.env.SUPABASE_URL,500).replace(/\/$/,'')||PUBLIC_URL,key=service||PUBLIC_KEY;if(!url||!key)throw Object.assign(Error('Sincronização fiscal não configurada no servidor'),{status:500});return {url,key,service:!!service};}
async function db(path,method,payload){const {url,key}=env(),r=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,authorization:'Bearer '+key,'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:payload===undefined?undefined:JSON.stringify(payload)});if(!r.ok){const d=await r.json().catch(()=>null);throw Object.assign(Error(d&&d.message||'Banco recusou a alteração fiscal'),{status:502});}}
async function read(path){const {url,key}=env(),r=await fetch(url+'/rest/v1/'+path,{headers:{apikey:key,authorization:'Bearer '+key}});if(!r.ok){const d=await r.json().catch(()=>null);throw Object.assign(Error(d&&d.message||'Banco recusou a leitura fiscal'),{status:502});}return r.json();}
async function readAll(table,order){const out=[];for(let from=0;;from+=1000){const page=await read(table+'?select=*&order='+order+'.asc&offset='+from+'&limit=1000');out.push(...page);if(page.length<1000)break;}return out;}
function passOk(stored,password){stored=String(stored||'');password=String(password||'');if(!stored.startsWith('pbkdf2$'))return stored===password;const p=stored.split('$'),it=Number(p[1]);if(p.length!==4||!it||it<100000)return false;try{const got=crypto.pbkdf2Sync(password,Buffer.from(p[2],'hex'),it,32,'sha256').toString('hex');return got.length===p[3].length&&crypto.timingSafeEqual(Buffer.from(got),Buffer.from(p[3]));}catch(_){return false;}}
function sign(value){return crypto.createHmac('sha256',env().key).update(value).digest('base64url');}
function tokenFor(u){const raw=Buffer.from(JSON.stringify({u,exp:Date.now()+12*60*60*1000})).toString('base64url');return raw+'.'+sign(raw);}
function auth(b){const token=clean(b&&b.token,3000),p=token.split('.');if(p.length!==2||sign(p[0])!==p[1])throw Object.assign(Error('Sessão inválida'),{status:401});let data;try{data=JSON.parse(Buffer.from(p[0],'base64url').toString('utf8'));}catch(_){throw Object.assign(Error('Sessão inválida'),{status:401});}if(!data.u||Number(data.exp)<Date.now())throw Object.assign(Error('Sessão expirada'),{status:401});return data;}
function labels(rows,max){max=max||200;if(!Array.isArray(rows)||rows.length>max)throw Object.assign(Error('Lote de etiquetas inválido'),{status:400});return rows.map(r=>{if(!r||!clean(r.id,120))throw Object.assign(Error('Etiqueta inválida'),{status:400});return r;});}
async function run(b){const a=clean(b.action,40),at=new Date().toISOString();
 if(a==='login'){const u=clean(b&&b.auth&&b.auth.u,120),p=clean(b&&b.auth&&b.auth.p,1000);if(!u||!p)throw Object.assign(Error('Login inválido'),{status:401});const rows=await read('usuarios?select=u,p&u=ilike.'+encodeURIComponent(u)+'&active=eq.true&limit=1');if(!rows.length||!passOk(rows[0].p,p))throw Object.assign(Error('Login não autorizado'),{status:401});return {token:tokenFor(rows[0].u)};}
 if(a==='read_documents'){const [notes,roms]=await Promise.all([read('notas_fiscais?select=*&order=key.asc'),read('romaneios?select=*&order=key.asc')]);return {notes,roms};}
 if(a==='read_snapshot'){const [notes,roms,labelRows]=await Promise.all([readAll('notas_fiscais','key'),readAll('romaneios','key'),readAll('etiquetas','id')]);return {notes,roms,labels:labelRows,snapshot_at:at};}
 if(a==='read_label_index'){const keys=(b.doc_keys||[]).map(x=>clean(x,200)).filter(Boolean),from=Math.max(0,Number(b.from)||0);if(!keys.length||keys.length>20)throw Object.assign(Error('Documentos inválidos'),{status:400});const list=keys.map(x=>'"'+x.replace(/["\\]/g,'')+'"').join(',');return read('etiquetas?select=id,updated_at&doc_key=in.('+encodeURIComponent(list)+')&order=id.asc&offset='+from+'&limit=1000');}
 if(a==='read_labels_by_ids'){const ids=(b.ids||[]).map(x=>clean(x,120)).filter(Boolean);if(!ids.length||ids.length>300)throw Object.assign(Error('Etiquetas inválidas'),{status:400});const list=ids.map(x=>'"'+x.replace(/["\\]/g,'')+'"').join(',');return read('etiquetas?select=*&id=in.('+encodeURIComponent(list)+')&order=id.asc');}
 if(a==='upsert_labels')return db('etiquetas','POST',labels(b.rows));
 if(a==='delete_labels'){const ids=(b.ids||[]).map(x=>clean(x,120)).filter(Boolean);if(!ids.length||ids.length>200)throw Object.assign(Error('IDs inválidos'),{status:400});return db('etiquetas?id=in.('+ids.map(encodeURIComponent).join(',')+')','DELETE');}
 if(a==='reconcile_labels'){const key=clean(b.doc_key,200),rows=labels(b.rows||[],1000);if(!key)throw Object.assign(Error('Documento fiscal inválido'),{status:400});if(rows.some(r=>clean(r.doc_key,200)!==key))throw Object.assign(Error('Etiqueta fora do documento'),{status:400});const ids=rows.map(r=>clean(r.id,120));let path='etiquetas?doc_key=eq.'+encodeURIComponent(key);if(ids.length)path+='&id=not.in.('+ids.map(encodeURIComponent).join(',')+')';await db(path,'DELETE');for(let i=0;i<rows.length;i+=200)await db('etiquetas','POST',rows.slice(i,i+200));return;}
 if(a==='upsert_note'||a==='upsert_rom'){const row=b.row;if(!row||!clean(row.key,200)||!row.data)throw Object.assign(Error('Documento inválido'),{status:400});return db((a==='upsert_note'?'notas_fiscais':'romaneios'),'POST',{key:clean(row.key,200),data:row.data,updated_at:row.updated_at||at});}
 if(a==='delete_note'||a==='delete_rom'){const key=clean(b.key,200);if(!key)throw Object.assign(Error('Chave inválida'),{status:400});return db((a==='delete_note'?'notas_fiscais':'romaneios'),'POST',{key,data:{key,deleted:true,deletedAt:at},updated_at:at});}
 throw Object.assign(Error('Ação inválida'),{status:400});
}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('Access-Control-Allow-Methods','GET, POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-WMS-Request');if(req.method==='OPTIONS')return res.status(204).end();if(req.method==='GET')return res.status(200).json({ok:true,service:'fiscal-sync',version:'20260904.46',configured:true,service_role:!!process.env.SUPABASE_SERVICE_ROLE_KEY});if(req.method!=='POST')return res.status(405).json({ok:false,error:'Método não permitido'});if(!originOk(req))return res.status(403).json({ok:false,error:'Origem não autorizada'});if(limited(req))return res.status(429).json({ok:false,error:'Muitas operações'});try{const data=await run(body(req));return res.status(200).json(data===undefined?{ok:true}:{ok:true,data});}catch(e){const s=Number(e.status)||500;if(s>=500)console.error('[fiscal-sync]',e);return res.status(s).json({ok:false,error:clean(e.message,300)});}};
module.exports._test={originOk,body,labels,run,readAll};
